name: CI
on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install .[lint,test]
      - run: black --check .
      - run: isort .
      - run: flake8 .
      - run: mypy src/ tests/
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install .[release]
      - run: python -m build .
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [lint]
    strategy:
      fail-fast: true
      matrix:
        python:
          - "2.7"
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"
          - "3.6"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - run: pip install .[test]
      - run: pytest tests
